name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install pytest
        run: python3 -m pip install pytest==8.4.2
      - name: Run tests
        run: python3 -m pytest -q
